config/routes.rb
# MODELS ARE USUALLY SINGULAR, CONTROLLERS ARE USUALLY PLURAL

Betastore::Application.routes.draw do

  get    '/log_in' => 'log_ins#new',     as: 'log_in'
  post   '/log_in' => 'log_ins#create'
  delete '/log_in' => 'log_ins#destroy', as: 'log_out'

  get  '/sign_up' => 'customers#new', as: 'sign_up'
  post '/sign_up' => 'customers#create'

  get  '/verify/:token' => 'customers#verify', as: 'verify_customer'

  get '/fail' => 'fail#fail'

  namespace :admin do
    resources :products
    get  '/login' => 'logins#new', as: 'logins'
    post '/login' => 'logins#create'
  end

  resources :subscriptions

  get '/products'     => 'products#index', as: 'products'
  get '/products/:id' => 'products#show',  as: 'product'

  post '/products/:product_id/add_to_cart' => 'carts#create',
    as: 'add_product_to_cart'

  resource :cart
  resources :orders

  root 'products#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
  has_many :credit_cards

  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  after_create :send_verification_email

  def self.verify(token)
    customer_id = Rails.application.message_verifier('customer').verify(token)
    customer = Customer.find(customer_id)
    customer.update!(verified_at: Time.current) unless customer.verified_at
    customer
  rescue => ex
    logger.error "Could not verify user: #{ex.class} #{ex.message}"
    nil
  end

  def send_verification_email
    CustomerMailer.welcome(self).deliver
  end
end

#WHAT I HAD BEFORE

# class Customer < ActiveRecord::Base
#   #has_many = can have many orders, line_items,
#   #products etc.
#   has_many :orders
#   has_many :line_items, :through => :orders
#   has_many :products, :through => :line_items
#   has_many :credit_cards
# end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to root_path
    else
      render :new
    end
  end

  def verify
    customer = Customer.verify(params[:token])

    if customer
      set_current_customer(customer)
      redirect_to root_path, notice: 'Your account is confirmed'
    else
      redirect_to root_path, alert: 'The verification link is invalid'
    end
  end

  private
    def customer_params
      params.require(:customer).permit(:name, :email, :password, :password_confirmation)
    end

end


# class CustomersController < ApplicationController
#   before_action :set_customer, only: [:show, :edit, :update, :destroy]

#   # GET /customers
#   # GET /customers.json
#   def index
#     @customers = Customer.all
#   end

#   # GET /customers/1
#   # GET /customers/1.json
#   def show
#   end

#   # GET /customers/new
#   def new
#     @customer = Customer.new
#   end

#   # GET /customers/1/edit
#   def edit
#   end

#   # POST /customers
#   # POST /customers.json
#   def create
#     @customer = Customer.new(customer_params)

#     respond_to do |format|
#       if @customer.save
#         format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
#         format.json { render action: 'show', status: :created, location: @customer }
#       else
#         format.html { render action: 'new' }
#         format.json { render json: @customer.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # PATCH/PUT /customers/1
#   # PATCH/PUT /customers/1.json
#   def update
#     respond_to do |format|
#       if @customer.update(customer_params)
#         format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
#         format.json { head :no_content }
#       else
#         format.html { render action: 'edit' }
#         format.json { render json: @customer.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /customers/1
#   # DELETE /customers/1.json
#   def destroy
#     @customer.destroy
#     respond_to do |format|
#       format.html { redirect_to customers_url }
#       format.json { head :no_content }
#     end
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_customer
#       @customer = Customer.find(params[:id])
#     end

#     # Never trust parameters from the scary internet, only allow the white list through.
#     def customer_params
#       params.require(:customer).permit(:name, :email, :password)
#     end
# end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer, url: sign_up_path) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.password %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>Signup</h1>

<%= render 'form' %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @customer.password %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>