config/routes.rb
# MODELS ARE USUALLY SINGULAR, CONTROLLERS ARE USUALLY PLURAL

Betastore::Application.routes.draw do

  get    '/log_in' => 'log_ins#new',     as: 'log_in'
  post   '/log_in' => 'log_ins#create'
  delete '/log_in' => 'log_ins#destroy', as: 'log_out'

  get  '/sign_up' => 'customers#new', as: 'sign_up'
  post '/sign_up' => 'customers#create'

  get  '/verify/:token' => 'customers#verify', as: 'verify_customer'

  get '/fail' => 'fail#fail'

  namespace :admin do
    resources :products
    get  '/login' => 'logins#new', as: 'logins'
    post '/login' => 'logins#create'
  end

  resources :subscriptions

  get '/products'     => 'products#index', as: 'products'
  get '/products/:id' => 'products#show',  as: 'product'

  post '/products/:product_id/add_to_cart' => 'carts#create',
    as: 'add_product_to_cart'

  resource :cart
  resources :orders

  root 'products#index'

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def create
    add_to_cart(params[:product_id])
    redirect_to cart_path,
      info: "product #{params[:product_id]} was added to your cart"
  end

  def show
    @order = Order.from_cart(cart)
  end

protected
  def add_to_cart(product_id)
    cart[product_id.to_i] += 1
  end

end

# class CartsController < ApplicationController

#   def create
#     add_to_cart(params[:product_id])
#     redirect_to cart_path,
#       info: "product #{params[:product_id]} was added to your cart"
#   end

#   def show
#     @order = Order.from_cart(cart)
#   end

# protected
#   def cart
#     session[:cart] ||= Hash.new(0)
#   end

#   def add_to_cart(product_id)
#     cart[product_id.to_i] += 1
#   end

# end

app/views/carts/show.html.erb
<h1>Your Cart</h1>

<table class="table">
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Unit Price</th>
    <th>Total Price</th>
  </tr>
  <% for line_item in @order.line_items %>
    <tr>
      <td><%= line_item.product.name %></td>
      <td><%= line_item.quantity %></td>
      <td><%= number_to_currency line_item.product.price %></td>
      <td><%= number_to_currency line_item.total_price %></td>
    </tr>
  <% end %>
  <tr>
    <td colspan="3"></td>
    <td><%= number_to_currency @order.total_amount %></td>
  </tr>
</table>

<p>
  <%= link_to "Checkout", new_order_path, class: 'btn btn-success' %>
</p>