config/routes.rb
# MODELS ARE USUALLY SINGULAR, CONTROLLERS ARE USUALLY PLURAL

Betastore::Application.routes.draw do

  get    '/log_in' => 'log_ins#new',     as: 'log_in'
  post   '/log_in' => 'log_ins#create'
  delete '/log_in' => 'log_ins#destroy', as: 'log_out'

  get  '/sign_up' => 'customers#new', as: 'sign_up'
  post '/sign_up' => 'customers#create'

  get  '/verify/:token' => 'customers#verify', as: 'verify_customer'

  get '/fail' => 'fail#fail'

  namespace :admin do
    resources :products
    get  '/login' => 'logins#new', as: 'logins'
    post '/login' => 'logins#create'
  end

  resources :subscriptions

  get '/products'     => 'products#index', as: 'products'
  get '/products/:id' => 'products#show',  as: 'product'

  post '/products/:product_id/add_to_cart' => 'carts#create',
    as: 'add_product_to_cart'

  resource :cart
  resources :orders

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  include PgSearch

  has_many :categorizations
  has_many :categories, :through => :categorizations

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0, allow_blank: true }

  pg_search_scope :search, :against => :name
  scope :min_price, -> (price) { where('price >= ?', price) }
  scope :max_price, -> (price) { where('price <= ?', price) }

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

#WHAT I HAD BEFORE

# class Product < ActiveRecord::Base
#   has_many :line_items
#   has_many :orders, :through => :line_items
#   has_many :categorizations
#   has_many :categories, :through => :categorizations
# end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  def index
    if logged_in?
      @products = Product.order('name')
    else
      redirect_to admin_login_path, alert: 'Please log in to continue'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path,
        success: "Product ##{@product.id} was created"
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path,
        success: "Product ##{@product.id} was updated"
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:success] = "Product ##{@product.id} was deleted"
    else
      flash[:danger] = "Product ##{@product.id} could not be deleted"
    end
    redirect_to admin_products_path
  end

protected
  def product_params
    params.require(:product).permit(:name, :price)
  end
end

#################
#WHAT I HAD BEFORE
#################

# class Admin::ProductsController < ApplicationController
#   #SEE LINE 7 FOR OTHER VARIANT OF LAYOUT
#   layout 'admin'

#   before_action :require_login

#   #DON'T NEED THIS ANYMORE... SEE INDEX FUNC BELOW AS WELL AS SECURITY SLIDES
#   # def index
#   #   if logged_in?
#   #     @products = Product.order('name').to_a
#   #   else
#   #     redirect_to admin_login_path, alert: 'Please log in to continue'
#   #   end
#   # end

#     def index
#       @products = Product.order('name').to_a
#     end


#   def show
#     # params is a method that returns a hash
#     #params[:id]
#     #SEE http://pjb3.github.io/back-end-web-development/03_sql_models_routing_controllers/routing#22
#     #This is the answer to ex 1.
#     @product = Product.find(params[:id])
#   end

#   def new
#     @product = Product.new
#   end

#   def create
#     @product = Product.new(product_params)
#     if @product.save
#       redirect_to admin_products_path,
#         success: "Product #{@product.id} was created"
#     else
#       render 'new'
#     end
#   end

#   def update
#     @product = Product.find(params[:id])
#       if @product.update(product_params)
#       redirect_to admin_products_path,
#         success: "Product ##{@product.id} was updated"
#       else
#       render 'edit'
#       end
#   end

#   def edit
#     @product = Product.edit(params[:id])
#   end

#   def destroy
#     @product = Product.find(params[:id])
#     @product.destroy
#     redirect_to admin_products_path, notice: "Product #{@product_id} has been deleted"
#   end

#   # protected means these methods can't be called as an action...
#   # They are used by actions
#   protected

#   #DO NOT USE ANYMORE... SEE NEW product_params BELOW, THIS WORKS WITH BRAKEMAN
#   # def product_params
#   #   params.require(:product).permit!
#   # end

#   def product_params
#     params.require(:product).permit(:name, :price)
#   end

#   def logged_in?
#     session[:user_id].present?
#   end

#   def require_login
#     unless logged_in?
#       redirect_to admin_login_path, danger: 'Please log in to continue'
#   end
# end

# end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :require_login

  def index
    @products = Product.order('name').limit(50)

    for param in %i[search min_price max_price]
      if params[param].present?
        @products = @products.send(param, params[param])
      end
    end

    respond_to do |format|
      format.html
      format.json do
        render json: @products
      end
    end
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/views/admin/products/_form.html.erb
<%= ender 'shared/errors', object: @product %>

<%= form_for [:admin, @product], html: {class: 'form-horizontal', role: 'form' } do |f| %>

  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, class: 'col-sm-2 control-label'%>
    <div class="col-sm-10">
    <%= f.text_field :price, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
     <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  </div>

<% end %>

app/views/admin/products/edit.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Products", admin_products_path %></li>
  <li><%= link_to @product.name, admin_products_path(@product) %></li>
  <li class="active">Active Products</li>
</ol>

<%= render 'form' %>

app/views/admin/products/index.html.erb
<h1>Products</h1>

<p>
  <%= link_to "New Product", new_admin_product_path, class: 'btn btn-primary' %>
</p>

<table class="table table-hover table-bordered">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Price</th>
    <th>Created At</th>
  </tr>
  <% for product in @products %>
    <tr>
      <td><%= link_to product.id, admin_product_path(product) %></td>
      <td><%= link_to product.name, admin_product_path(product) %></td>
      <td><%= product.price %></td>
      <td><%= product.created_at %></td>
    </tr>
  <% end %>
</table>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<% if @product.errors.present? %>
  <ul style="color: red">
  <% @product.errors.full_messages.each do |err| %>
    <li><%= err %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for [:admin, @product] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.submit "Save" %>
<% end %>

app/views/admin/products/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Products", admin_products_path %></li>
  <li><%= link_to @product.name, admin_products_path(@product) %></li>
</ol>

  <table>
    <tr>
      <th style="text-align: right">name</th>
      <td style="text-align: left; padding-left: 20px"><%= @product.name %></td>
    </tr>
    <tr>
      <th style="text-align: right">price</th>
      <td style="text-align: left; padding-left: 20px"><%= number_to_currency @product.price %></td>
    </tr>
    <tr>
      <th style="text-align: right">image</th>
      <td style="text-align: left; padding-left: 20px"><%=image_tag @product.image_url, alt: @product.image_url %></td>
    </tr>

    <tr>
      <th style="text-align: right">Created:</th>
      <td style="text-align: left; padding-left: 20px"><%= time_ago_in_words @product.created_at %> ago on <%= @product.created_at.strftime('%B %d, %Y @ %k:%M:%S %Z') %></td>
    </tr>

</table>


<%= link_to "Back to products", admin_products_path %>
<%= link_to "Edit", edit_admin_product_path %>
<%= link_to "Delete", admin_product_path, method: :delete,
  confirm: "Are you sure?" %>